is_alive: fix fd leak in error path
Found by cppcheck:

  Checking meminfo.c ...
  meminfo.c:122:9: error: Resource leak: f [resourceLeak]
          return false;
          ^

Fix it by introducing a "res" variable and closing the
fd earlies.