tests: replace Test_parse_proc_pid_stat_Self with Test_parse_proc_pid_stat_1
Running the test against ourselves is unreliable due to golang thread
multiplexing.

Hopefully init (pid1) is almost always is state 'S' (sleeping).

=== RUN   Test_parse_proc_pid_stat_Self
    testsuite_unit_test.go:247:
        have=earlyoom_testsuite._Ctype_struct___2{state:83, ppid:237, num_threads:6}
        want=earlyoom_testsuite._Ctype_struct___2{state:82, ppid:237, num_threads:6}
--- FAIL: Test_parse_proc_pid_stat_Self (0.00s)